Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-10"
    
#  config.vm.network "forwarded_port", guest: 80, host: 8080
 # config.vm.network "forwarded_port", guest: 81, host: 8081

   config.vm.provider "virtualbox" do |vb|
  
    vb.memory = "1024"
    vb.name = "Debian10"
   end
   config.vm.hostname = "Debian10"
 # config.vm.provision "shell", inline: <<-SHELL
 #    apt-get update
 #  apt-get install -y apache2
 #  SHELL
 #  config.vm.provision "shell", path: "provision.sh"
end
 
