---

- name: Install Apache
  become: yes
  hosts: all
  tasks:

  - name: Install Apache and php
    apt:
           pkg:
           - php 
           - apache2
           state: present
  - name: copy html
    copy:
        src: /vagrant/index.html
        dest: /var/www/html
  - name: Http & PHP
    shell: echo '<VirtualHost *:80>  
                  DocumentRoot "/var/www/Http/index.html"
                  </VirtualHost>
                  <VirtualHost *:81>  
                  DocumentRoot "/var/www/php/index.php"
                  </VirtualHost>' >> /etc/apache2/http.conf
    args:
        chdir: /etc/apache2
        creates: http.conf
  - name: Create dir php
    become: true
    file:
      path: /var/www/php
      state: directory
      owner: www-data
      mode: '0755'  
  - name: copy php
    copy:
            src: /vagrant/index.php
            dest: /var/www/php          
  - name: php ports
    shell: echo 'Listen 81' >> /etc/apache2/ports.conf
    args:
        chdir: /etc/apache2
  - name: PHP Sites Avalable
    shell: echo '<VirtualHost *:81>
                \nServerAdmin webmaster@localhost
                \nDocumentRoot /var/www/php
                \nErrorLog ${APACHE_LOG_DIR}/error.log
                \nCustomLog ${APACHE_LOG_DIR}/access.log combined
                \n</VirtualHost>' > /etc/apache2/sites-available/000-default.conf
    args:
        chdir: /etc/apache2/sites-available
    notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted