---

- name: Install & configure LXC 
  become: yes
  hosts: all
  tasks:

  - name: Install LXC and pyton
    package:
      name:
        - lxc
        - lxc-templates
        - lxc-dev
        - python3-pip
        - python3-lxc
      state: latest
      update_cache: true
  
  - name: make dir and file
    file:
        path: /etc/default/lxc-net
        state: touch
  - file:    
        path: /etc/lxc/lxc-usernet
        state: touch
  - file:    
        path: ~/.config/lxc
        state: directory 
  - file:    
        path: ~/.config/lxc/
        state: directory              
  - file:
        path: /var/lib/lxc/c1/rootfs/var/www/html
        state: directory
  - file:
        path: /var/lib/lxc/c2/rootfs/var/www/php
        state: directory
  
  - name: default.conf
    shell: echo "lxc.net.0.type = veth
                /nlxc.net.0.flags = up
                /nlxc.net.0.link = lxcbr0
                /nlxc.apparmor.profile = unconfined
                /nlxc.apparmor.allow_nesting = 1" > ~/.config/lxc/default.conf
    args:
        chdir: ~/.config/lxc/
        creates: default.conf
  
  - name: lxc-usernet
    shell: echo "vagrant veth lxcbr0 10"  >> /etc/lxc/lxc-usernet
    args:
         chdir: /etc/lxc
  
  - name: lxc-dhcp
    shell: echo "dhcp-host=c1,10.0.3.80
                \ndhcp-host=c2,10.0.3.81" >> /etc/default/lxc-dhcp.conf
    args:
         chdir: /etc/default/
         creates: lxc-dhcp.conf
  
  - name: conf lan
    lineinfile:
        path: /etc/default/lxc-net
        line: "{{item}}"
    with_items:
         - USE_LXC_BRIDGE="true"
         - LXC_BRIDGE="lxcbr0" 
         - LXC_ADDR="10.0.3.1"
         - LXC_NETMASK="255.255.255.0"
         - LXC_NETWORK="10.0.3.0/24"
         - LXC_DHCP_RANGE="10.0.3.2,10.0.3.254"
         - LXC_DHCP_MAX="253"
         - LXC_DHCP_CONFILE="/etc/default/lxc-dhcp.conf"
         - LXC_DOMAIN=""
  ##############################
  - name: restart lxc-net 
    service:
        name: lxc-net
        state: restarted
  ##############################      
  - name: make c1
    lxc_container:
        name: c1
        template: download
        template_options: --dist centos --release 8-Stream --arch amd64 --keyserver hkp://keyserver.ubuntu.com 
        state: started
        container_command: |
          sleep 10
          yum -y install httpd
          yum -y install php
          systemctl enable httpd
          systemctl start httpd
          sleep 5   
    
  - name: make c2
    lxc_container:
      name: c2
      template: download
      template_options: --dist centos --release 8-Stream --arch amd64 --keyserver hkp://keyserver.ubuntu.com  
      state: started
      container_command: |
          sleep 10
          yum -y install httpd
          yum -y install php
          systemctl enable httpd
          systemctl start httpd   
          sleep 5          
  
  - name: copy html & php
    copy: 
      src: /vagrant/index.html
      dest: /var/lib/lxc/c1/rootfs/var/www/html/
  - copy:
      src: /vagrant/index.php
      dest: /var/lib/lxc/c2/rootfs/var/www/php/
 
  - name: Add port 81 conteiner 2
    replace:
      path: /var/lib/lxc/c2/rootfs/etc/httpd/conf/httpd.conf
      regexp: 'Listen 80'
      replace: 'Listen 81'

  - name: VirtualHost conteiner 2
    file:
      path: /var/lib/lxc/c2/rootfs/etc/httpd/conf.d/default.conf
      state: touch
  - lineinfile:
      path: /var/lib/lxc/c2/rootfs/etc/httpd/conf.d/default.conf
      line: "{{item}}"
    with_items:
       - <VirtualHost *:81>
       - DocumentRoot /var/www/php/ 
       - </VirtualHost>
  
  - name: VirtualHost conteiner 1
    file:
      path: /var/lib/lxc/c1/rootfs/etc/httpd/conf.d/http.conf
      state: touch
  - lineinfile:
      path: /var/lib/lxc/c1/rootfs/etc/httpd/conf.d/http.conf
      line: "{{item}}"
    with_items:
       - <VirtualHost *:80>
       - DocumentRoot /var/www/html/ 
       - </VirtualHost>

########################################
  - name: Restart Apache c1
    lxc_container:
      name: c1
      container_command: |
        systemctl restart httpd
  - name: Restart Apache c2
    lxc_container:
      name: c2
      container_command: |
        systemctl restart httpd

  - name: IPTABLES
    shell: iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 80 -j DNAT --to-destination 10.0.3.80
  - shell: iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 81 -j DNAT --to-destination 10.0.3.81