# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8081

config.vm.synced_folder ".", "/vagrant"


config.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  vb.name = "Ansible02_LXC"
 end
 config.vm.define "master", primary: true do |master|
  config.vm.provision "shell", inline: <<-SHELL
    apt update  
    apt install -y gnupg2
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main" >> /etc/apt/sources.list
    apt update
    apt install -y ansible
  SHELL
  config.vm.provision :ansible_local do |ansible|
    # Имя файла сценария
    ansible.playbook       = "playbookLXC.yml"

    # Именно этот параметр ограничивает, какие хосты из inventory доступны для
    #   выполнения сценария
    ansible.limit          = "all"

    # Имя файла инвентаря
    ansible.inventory_path = "inventory"
  end
end
end