Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8081

config.vm.synced_folder ".", "/home"

 config.vm.provider "virtualbox" do |vb|

  vb.memory = "1024"
  vb.name = "Ansible02"
 end
 config.vm.hostname = "Ansible02"
 config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo apt-get install ansible -y
#  apt-get install -y apache2
  SHELL
#config.vm.provision "shell", path: "provision_ansible_02.sh"
end