# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
    
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end
    
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.network "private_network", ip: "192.168.33.10"
      jenkins.vm.provision "shell", inline: <<-SHELL     
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
        /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null
        sudo apt-get update
        sudo apt install openjdk-11-jre -y
        sudo apt-get install ansible -y
        sudo apt-get install -y gnupg2
     
        SHELL
            
        jenkins.vm.provision :ansible_local do |ansible|
          ansible.playbook = "jenkins.yml"
          ansible.galaxy_role_file = "role_file.yml"
          ansible.galaxy_roles_path = "/usr/share/ansible/collections"
          ansible.galaxy_command = "sudo ansible-galaxy collection install -r%{role_file} -p%{roles_path} --force"

          ansible.groups   = {
            "jenkins" => ["jenkins.vm"],

            "all:vars" => { "ansible_ssh_extra_args": "-o StrictHostKeyChecking=no",
                            "ansible_connection": "ssh",
                            "ansible_user": "vagrant",
                            "ansible_password": "vagrant"}
          }
          ansible.host_vars = {
            "jenkins.vm"    => { "ansible_host": "192.168.33.10" },
          }
          ansible.limit = "all"
        end
      end  
      
      config.vm.provision "shell", inline: <<-SHELL
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
      SHELL
end