---

- name: Install Apache
  become: yes
  hosts: all
  tasks:
    # # # # # # # # - name: disable key check
    # # # # # # # #   ini_file:
    # # # # # # # #     path: /etc/ansible/ansible.cfg
    # # # # # # # #     section: defaults
    # # # # # # # #     option: host_key_checking
    # # # # # # # #     value: False
      #- name: Install apache2
      #  apt: name=apache2 state=latest
    - name: Install Apache and php
      apt:
           pkg:
           - php 
           - apache2
           state: present
    - name: copy html
      copy:
        src: /vagrant/index.html
        dest: /var/www/html

    - name: Http
      shell: echo '<VirtualHost *:80>  
                  DocumentRoot "/var/www/Http/index.html"
                  </VirtualHost>' >> /etc/apache2/http.conf
      args:
        chdir: /etc/apache2
        creates: http.conf
    - name: copy php
      copy:
        src: /vagrant/index.php
        dest: /var/www/php

    - name: php sites-available
      shell: echo '<VirtualHost *:81>  
                  DocumentRoot "/var/www/php/index.php"
                  </VirtualHost>' >> /etc/apache2/sites-available/000-default.conf
      args:
        chdir: /etc/apache2/sites-available   
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
        

##lxc-attach c1 -- mkdir -p /var/www/html
# # # # cp /home/index.html /var/lib/lxc/c1/rootfs/var/www/html
# # # # lxc-attach c1 -- touch /etc/apache2/http.conf 

# # # # echo "
# # # # <VirtualHost *:80>
# # # #   DocumentRoot "/var/www/html"
# # # # </VirtualHost>" >> /etc/apache2/http.confhttp.conf

# # # # lxc-attach c1 -- systemctl restart httpd
# # # # # Edit key-file permissions
# # # # - name: Touch the file, but add/remove some permissions
# # # #   hosts: node2
# # # #   tasks:
# # # #     - file:
# # # #         path: '{{ item.fpath }}'
# # # #         state: file
# # # #         owner: vagrant
# # # #         mode: u+rw,g-rwx,o-rwx
# # # #       loop:
# # # #         - { fpath: /home/vagrant/private_key_node0 }
# # # #         - { fpath: /home/vagrant/private_key_node1 }

# # # # # Playbook №1, будет выполняться только на хосте с именем node1
# # # # - name: Node1 config
# # # #   hosts: node1
# # # #   tasks:
# # # #     - debug:
# # # #         msg: "Running on {{ inventory_hostname }}"

# # # # # Playbook №2, будет выполняться только на хосте с именем node2
# # # # - name: Node2 config
# # # #   hosts: node2
# # # #   tasks:
# # # #     - debug:
# # # #         msg: "Running on {{ inventory_hostname }}"

# # # # - name: Common config
# # # #   hosts: all
# # # #   tasks:
# # # #     - debug:
# # # #         msg: "Running on {{ inventory_hostname }}"