---

- name: Install Apache
  become: yes
  hosts: all
  tasks:
    # # # # # # # # - name: disable key check
    # # # # # # # #   ini_file:
    # # # # # # # #     path: /etc/ansible/ansible.cfg
    # # # # # # # #     section: defaults
    # # # # # # # #     option: host_key_checking
    # # # # # # # #     value: False
      #- name: Install apache2
      #  apt: name=apache2 state=latest
    - name: Install Apache
      apt:
           pkg:
           - sshpass 
           - apache2
           state: present

# # # # # Edit key-file permissions
# # # # - name: Touch the file, but add/remove some permissions
# # # #   hosts: node2
# # # #   tasks:
# # # #     - file:
# # # #         path: '{{ item.fpath }}'
# # # #         state: file
# # # #         owner: vagrant
# # # #         mode: u+rw,g-rwx,o-rwx
# # # #       loop:
# # # #         - { fpath: /home/vagrant/private_key_node0 }
# # # #         - { fpath: /home/vagrant/private_key_node1 }

# # # # # Playbook №1, будет выполняться только на хосте с именем node1
# # # # - name: Node1 config
# # # #   hosts: node1
# # # #   tasks:
# # # #     - debug:
# # # #         msg: "Running on {{ inventory_hostname }}"

# # # # # Playbook №2, будет выполняться только на хосте с именем node2
# # # # - name: Node2 config
# # # #   hosts: node2
# # # #   tasks:
# # # #     - debug:
# # # #         msg: "Running on {{ inventory_hostname }}"

# # # # - name: Common config
# # # #   hosts: all
# # # #   tasks:
# # # #     - debug:
# # # #         msg: "Running on {{ inventory_hostname }}"