Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8081

config.vm.synced_folder ".", "/home"

 config.vm.provider "virtualbox" do |vb|

  vb.memory = "1024"
  vb.name = "ansible_01"
 end
 config.vm.hostname = "ansible_01"
# config.vm.provision "shell", inline: <<-SHELL
#    apt-get update
#  apt-get install -y apache2
#  SHELL
config.vm.provision "shell", path: "provision_ansible_01.sh"
end