Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "forwarded_port", guest: 81, host: 8081

config.vm.synced_folder ".", "/vagrant"


config.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  vb.name = "Ansible01"
  end
 ##### sudo systemctl restart apache2
# config.vm.define "Master" do |node|
#   node.vm.network "private_network", ip: "192.168.11.30"
# end

# config.vm.define "Client_1" do |node|
#   node.vm.network "private_network", ip: "192.168.11.31"
# end

# config.vm.define "Client_2" do |node|
#   node.vm.network "private_network", ip: "192.168.11.32"
 ##config.vm.provider "virtualbox" do |vb|
  
  ##sudo apt install sshpass
  ## node.vm.provision :file, source: '.vagrant/machines/Master/virtualbox/private_key', destination: '/home/vagrant/private_key_Master'
  ## node.vm.provision :file, source: '.vagrant/machines/Client_1/virtualbox/private_key', destination: '/home/vagrant/private_key_Client_1'
  ##node.vm.provision :file, source: '.vagrant/machines/Client_2/virtualbox/private_key', destination: '/home/vagrant/private_key_Client_2'
  ##node.vm.provision :ansible_local do |ansible|
  # # # # config.vm.provision "shell", inline: <<-SHELL
  # # # #   sudo apt install sshpass
  # # # # SHELL
  config.vm.provision :ansible_local do |ansible|
    # Имя файла сценария
    ansible.playbook       = "playbook.yml"

    # Именно этот параметр ограничивает, какие хосты из inventory доступны для
    #   выполнения сценария
    ansible.limit          = "all"

    # Имя файла инвентаря
    ####ansible.inventory_path = "inventory"
  end
#end
#end
  
#  config.vm.hostname = "Ansible01"
   ####config.vm.provision "shell", inline: <<-SHELL
  #    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
  #    sudo apt-get update
  #    sudo apt-get install ansible -y
  ####sudo apt install sshpass
# #  apt-get install -y apache2
   ####SHELL
#config.vm.provision "shell", path: "provision_ansible_01.sh"
end