Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/centos8"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081
  config.ssh.insert_key = false 
  
  config.vm.provider "virtualbox" do |vb|
  
    vb.memory = "1024"
    vb.name = "Centos8"
   end
   config.vm.hostname = "Centos8"
   config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provision "shell", inline: <<-SHELL
  sudo yum update
  sudo yum -y install httpd
  sudo systemctl start  httpd
  sudo firewall-cmd --permanent --add-service=http
  sudo firewall-cmd --reload
SHELL
config.vm.provision "shell", path: "ParametrCentos.sh"
end

